# Generated by Django 4.2.7 on 2023-11-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("decoder", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="code",
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="code",
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="model",
            name="code",
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name="model",
            name="name",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="year",
            name="code",
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name="year",
            name="year",
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
