# Generated by Django 4.2.7 on 2023-11-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AddField(
            model_name='productionyear',
            name='year',
            field=models.IntegerField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
