# Generated by Django 4.2.7 on 2023-11-13 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decoder', '0002_alter_country_options_productionyear_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin_code', models.CharField(max_length=17)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decoder.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='mark',
            name='code',
        ),
        migrations.RemoveField(
            model_name='model',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='productionyear',
            name='code',
        ),
        migrations.AlterModelOptions(
            name='country',
            options={},
        ),
        migrations.RemoveField(
            model_name='country',
            name='code',
        ),
        migrations.DeleteModel(
            name='CountryCode',
        ),
        migrations.DeleteModel(
            name='Mark',
        ),
        migrations.DeleteModel(
            name='MarkCode',
        ),
        migrations.DeleteModel(
            name='Model',
        ),
        migrations.DeleteModel(
            name='ProductionYear',
        ),
        migrations.DeleteModel(
            name='YearCode',
        ),
        migrations.AddField(
            model_name='car',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decoder.country'),
        ),
        migrations.AddField(
            model_name='car',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decoder.manufacturer'),
        ),
        migrations.AddField(
            model_name='car',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='decoder.region'),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decoder.year'),
        ),
    ]
