# Generated by Django 4.2.7 on 2023-11-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "decoder",
            "0003_alter_brand_code_alter_country_code_alter_model_code_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="model",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="year",
            name="year",
            field=models.CharField(max_length=4),
        ),
    ]
