# Generated by Django 4.2.7 on 2023-11-22 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decoder', '0004_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='name',
            new_name='model',
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='decoder.model'),
            preserve_default=False,
        ),
    ]
